version: 0.1
environment_variables:
  plaintext:
    S3_BUCKET: "drygielski.com"
    BUILD_ENV: "prod"

phases:
  install:
    commands:
      - npm install
      - npm install -g @angular/cli
      - npm install --save @angular/material @angular/cdk @angular/animations
      - npm install --save hammerjs
  build:
    commands:
      - ng build --env=${BUILD_ENV}
  post_build:
    commands:
      - aws s3 cp dist s3://${S3_BUCKET}/ --recursive

artifacts:
#  files:
#        - '**/*'
    base-directory: 'dist*'
    discard-paths: yes
